spring:
  application:
    name: chl-msa-customer

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: "classpath:db/migration"
    sql-migration-suffixes: ".sql"
    sql-migration-prefix: V
    sql-migration-separator: "__"
    url: jdbc:postgresql://localhost:3539/postgres
    user: ${POSTGRESQL_USERNAME:postgres}
    password: ${POSTGRESQL_PASSWORD:password}
    schemas: ${POSTGRESQL_SCHEMA:challenge}

challenge:
  base-path: /api/v1/customers
  postgresql:
    host: ${ONB_POSTGRESQL_HOST:localhost}
    port: ${ONB_POSTGRESQL_PORT:3539}
    dbname: ${POSTGRESQL_DBNAME:postgres}
    schema: ${POSTGRESQL_SCHEMA:challenge}
    username: ${POSTGRESQL_USERNAME:postgres}
    password: ${POSTGRESQL_PASSWORD:password}
    ssl-mode: ${POSTGRESQL_SSL:disable}

logging:
  level:
    org.flywaydb: DEBUG
